WITH
T1 AS (
	SELECT CUR_ID, SUM(mat_precio) PROYECTADO 
	FROM MATRICULA
	GROUP BY CUR_ID
),
T2 AS (
	SELECT CUR_ID, SUM(pag_importe) RECAUDADO 
	FROM PAGO
	GROUP BY CUR_ID
)
SELECT 
	C.cur_id, C.cur_nombre, T1.PROYECTADO,
	ISNULL(T2.RECAUDADO,0) RECAUDADO,
	T1.PROYECTADO - ISNULL(T2.RECAUDADO,0) FALTA
FROM CURSO C
JOIN T1 ON C.cur_id = T1.CUR_ID
LEFT JOIN T2 ON C.cur_id = T2.cur_id;
GO