-- Activar la base de datos

USE [SANTO-TOMAS];
GO

-- TABLA PACIENTE

SET IDENTITY_INSERT [dbo].[PACIENTE] ON;
GO

INSERT INTO PACIENTE(IDPACIENTE,NOMBRE) VALUES(1,'JUAN PEREZ');
INSERT INTO PACIENTE(IDPACIENTE,NOMBRE) VALUES(2,'LEONARDO LEON');
INSERT INTO PACIENTE(IDPACIENTE,NOMBRE) VALUES(3,'NOELIA LAZO');
INSERT INTO PACIENTE(IDPACIENTE,NOMBRE) VALUES(4,'CARMEN SANCHEZ');
INSERT INTO PACIENTE(IDPACIENTE,NOMBRE) VALUES(5,'ALAN GARCIA');
INSERT INTO PACIENTE(IDPACIENTE,NOMBRE) VALUES(6,'CELESTE RIOS');
GO

SET IDENTITY_INSERT [dbo].[PACIENTE] OFF;
GO

SELECT * FROM [dbo].[PACIENTE];
GO


-- TABLA MEDICO

SET IDENTITY_INSERT [dbo].[MEDICO] ON;
GO

INSERT INTO MEDICO(IDMEDICO,NOMBRE) VALUES(501,'GUSTAVO CORONEL');
INSERT INTO MEDICO(IDMEDICO,NOMBRE) VALUES(502,'BRYAN DELGADO');
INSERT INTO MEDICO(IDMEDICO,NOMBRE) VALUES(503,'JULIA OSORIO');
INSERT INTO MEDICO(IDMEDICO,NOMBRE) VALUES(504,'MARTINA GONZALE');
INSERT INTO MEDICO(IDMEDICO,NOMBRE) VALUES(505,'FERNANDO RAMIREZ');
INSERT INTO MEDICO(IDMEDICO,NOMBRE) VALUES(506,'ARIADNA GUZMAN');
GO

SET IDENTITY_INSERT [dbo].[MEDICO] OFF;
GO

SELECT * FROM [dbo].[MEDICO];
GO


-- TABLA HABITACION

SET IDENTITY_INSERT [dbo].[HABITACION] ON;
GO

INSERT INTO HABITACION(IDHABITACION,ETIQUETA,PABELLON,PISO,DISPONIBLE) VALUES(601,'PA-601','PA',4,1);
INSERT INTO HABITACION(IDHABITACION,ETIQUETA,PABELLON,PISO,DISPONIBLE) VALUES(602,'PA-602','PA',4,1);
INSERT INTO HABITACION(IDHABITACION,ETIQUETA,PABELLON,PISO,DISPONIBLE) VALUES(603,'PA-603','PA',4,0);
INSERT INTO HABITACION(IDHABITACION,ETIQUETA,PABELLON,PISO,DISPONIBLE) VALUES(604,'PA-604','PA',4,1);
INSERT INTO HABITACION(IDHABITACION,ETIQUETA,PABELLON,PISO,DISPONIBLE) VALUES(605,'PA-605','PA',4,1);
GO

SET IDENTITY_INSERT [dbo].[HABITACION] OFF;
GO

SELECT * FROM HABITACION;
GO

